<?php

use Illuminate\Database\Seeder;

class ClientsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

      DB::table('clients')->insert([
            // 'id' => '1',
            'user_id' => '2',
            'firstName' => 'John',
            'lastName' => 'Doe',
            'ssn' => '553485488',
            'medicaid' => '00048466',
            'birth_month' => '10',
            'birth_day' => '2',
            'birth_year' => '2017',
            'due_month' => '10',
            'due_day' => '20',
            'due_year' => '2017',
            'ethnicity' => 'Black',
            'medical_home' => 'Yes',
            'marital_status' => 'single',
            'number_of_persons' => '2',
            'income' => '25,001-25,000',
            'insurance' => 'Medicaid',
            'primary_care' => 'Other',
            'prenatal_vitamin' => 'Yes',
            'nutritional_counseling' => 'Yes',
            'smoking_in_home' => 'Yes',
            'employment_status' => 'Unemployed- Not seeking work- Barriers',
            'education_enrollment' => 'High School',
            'educational_level' => 'Some high school',
            'parent_first_name' => 'Sue',
            'parent_last_name' => 'Jones',
            'parent_ssn' => '555555555',
            'parent_medicaid' => '575757575',
            'partner_first_name' => 'Sam',
            'partner_last_name' => 'Jones',
            'partner_ssn' => '444444444',
            'partner_medicaid' => '444444444444',
            'partner_employment' => 'Unemployed- Not seeking work- Barriers',
            'partner_education' => '8th Grade or below',
            'partner_education_status' => 'GED'
       ]);

       DB::table('clients')->insert([
             // 'id' => '2',
             'user_id' => '2',
             'firstName' => 'Jane',
             'lastName' => 'Doe',
             'ssn' => '999999999',
             'medicaid' => '757575757',
             'birth_month' => '2',
             'birth_day' => '10',
             'birth_year' => '2017',
             'due_month' => '2',
             'due_day' => '12',
             'due_year' => '2017',
             'ethnicity' => 'White',
             'medical_home' => 'Yes',
             'marital_status' => 'Married',
             'number_of_persons' => '4',
             'income' => '50,001-70,000',
             'insurance' => 'Private',
             'primary_care' => 'Private',
             'prenatal_vitamin' => 'Yes',
             'nutritional_counseling' => 'Yes',
             'smoking_in_home' => 'No',
             'employment_status' => 'Employed full time',
             'education_enrollment' => 'Not Enrolled',
             'educational_level' => '4 Year Degree',
             'parent_first_name' => 'Betty',
             'parent_last_name' => 'Boo',
             'parent_ssn' => '666666666',
             'parent_medicaid' => '435443354',
             'partner_first_name' => 'Bob',
             'partner_last_name' => 'Boo',
             'partner_ssn' => '989989898',
             'partner_medicaid' => '039484855',
             'partner_employment' => 'Employed part time',
             'partner_education' => '2 Year Degree',
             'partner_education_status' => 'Not Enrolled'
        ]);

        DB::table('clients')->insert([
              // 'id' => '1',
              'user_id' => '3',
              'firstName' => 'Sally',
              'lastName' => 'Rally',
              'ssn' => '32323232',
              'medicaid' => '323232323',
              'birth_month' => '8',
              'birth_day' => '22',
              'birth_year' => '2017',
              'due_month' => '9',
              'due_day' => '22',
              'due_year' => '2017',
              'ethnicity' => 'Hispanic',
              'medical_home' => 'Yes',
              'marital_status' => 'single',
              'number_of_persons' => '4',
              'income' => '25,001-30,000',
              'insurance' => 'Medicaid',
              'primary_care' => 'Health Department',
              'prenatal_vitamin' => 'No',
              'nutritional_counseling' => 'No',
              'smoking_in_home' => 'No',
              'employment_status' => 'Employed part time',
              'education_enrollment' => 'Not Enrolled',
              'educational_level' => 'Some high school',
              'parent_first_name' => 'Shelly',
              'parent_last_name' => 'Davis',
              'parent_ssn' => '222222222',
              'parent_medicaid' => '432543243',
              'partner_first_name' => 'Mark',
              'partner_last_name' => 'Magic',
              'partner_ssn' => '3333333333',
              'partner_medicaid' => '434343434343',
              'partner_employment' => 'Employed full time',
              'partner_education' => 'Some high school',
              'partner_education_status' => 'GED'
         ]);

         DB::table('clients')->insert([
               // 'id' => '1',
               'user_id' => '3',
               'firstName' => 'Johnny',
               'lastName' => 'Joe',
               'ssn' => '98898989',
               'medicaid' => '434234234',
               'birth_month' => '11',
               'birth_day' => '30',
               'birth_year' => '2016',
               'due_month' => '11',
               'due_day' => '29',
               'due_year' => '2016',
               'ethnicity' => 'White',
               'medical_home' => 'No',
               'marital_status' => 'single',
               'number_of_persons' => '2',
               'income' => '10,001-15,000',
               'insurance' => 'Medicaid',
               'primary_care' => 'Clinic',
               'prenatal_vitamin' => 'Yes',
               'nutritional_counseling' => 'Yes',
               'smoking_in_home' => 'No',
               'employment_status' => 'Unemployed- Not seeking work- Barriers',
               'education_enrollment' => 'High School',
               'educational_level' => 'Some high school',
               'parent_first_name' => 'Yolanda',
               'parent_last_name' => 'Young',
               'parent_ssn' => '4342343423',
               'parent_medicaid' => '656556456',
               'partner_first_name' => 'Paul',
               'partner_last_name' => 'Pantella',
               'partner_ssn' => '11111111',
               'partner_medicaid' => '323212233',
               'partner_employment' => 'Unemployed- Not seeking work- Barriers',
               'partner_education' => '8th Grade or below',
               'partner_education_status' => 'High School'
          ]);

          DB::table('clients')->insert([
                // 'id' => '1',
                'user_id' => '2',
                'firstName' => 'John',
                'lastName' => 'Doe',
                'ssn' => '553485488',
                'medicaid' => '00048466',
                'birth_month' => '10',
                'birth_day' => '2',
                'birth_year' => '2017',
                'due_month' => '10',
                'due_day' => '20',
                'due_year' => '2017',
                'ethnicity' => 'Black',
                'medical_home' => 'Yes',
                'marital_status' => 'single',
                'number_of_persons' => '2',
                'income' => '25,001-25,000',
                'insurance' => 'Medicaid',
                'primary_care' => 'Other',
                'prenatal_vitamin' => 'Yes',
                'nutritional_counseling' => 'Yes',
                'smoking_in_home' => 'Yes',
                'employment_status' => 'Unemployed- Not seeking work- Barriers',
                'education_enrollment' => 'High School',
                'educational_level' => 'Some high school',
                'parent_first_name' => 'Sue',
                'parent_last_name' => 'Jones',
                'parent_ssn' => '555555555',
                'parent_medicaid' => '575757575',
                'partner_first_name' => 'Sam',
                'partner_last_name' => 'Jones',
                'partner_ssn' => '444444444',
                'partner_medicaid' => '444444444444',
                'partner_employment' => 'Unemployed- Not seeking work- Barriers',
                'partner_education' => '8th Grade or below',
                'partner_education_status' => 'GED'
           ]);

           DB::table('clients')->insert([
                 // 'id' => '1',
                 'user_id' => '2',
                 'firstName' => 'John',
                 'lastName' => 'Doe',
                 'ssn' => '553485488',
                 'medicaid' => '00048466',
                 'birth_month' => '10',
                 'birth_day' => '2',
                 'birth_year' => '2017',
                 'due_month' => '10',
                 'due_day' => '20',
                 'due_year' => '2017',
                 'ethnicity' => 'Black',
                 'medical_home' => 'Yes',
                 'marital_status' => 'single',
                 'number_of_persons' => '2',
                 'income' => '25,001-25,000',
                 'insurance' => 'Medicaid',
                 'primary_care' => 'Other',
                 'prenatal_vitamin' => 'Yes',
                 'nutritional_counseling' => 'Yes',
                 'smoking_in_home' => 'Yes',
                 'employment_status' => 'Unemployed- Not seeking work- Barriers',
                 'education_enrollment' => 'High School',
                 'educational_level' => 'Some high school',
                 'parent_first_name' => 'Sue',
                 'parent_last_name' => 'Jones',
                 'parent_ssn' => '555555555',
                 'parent_medicaid' => '575757575',
                 'partner_first_name' => 'Sam',
                 'partner_last_name' => 'Jones',
                 'partner_ssn' => '444444444',
                 'partner_medicaid' => '444444444444',
                 'partner_employment' => 'Unemployed- Not seeking work- Barriers',
                 'partner_education' => '8th Grade or below',
                 'partner_education_status' => 'GED'
            ]);

            DB::table('clients')->insert([
                  // 'id' => '1',
                  'user_id' => '2',
                  'firstName' => 'John',
                  'lastName' => 'Doe',
                  'ssn' => '553485488',
                  'medicaid' => '00048466',
                  'birth_month' => '10',
                  'birth_day' => '2',
                  'birth_year' => '2017',
                  'due_month' => '10',
                  'due_day' => '20',
                  'due_year' => '2017',
                  'ethnicity' => 'Black',
                  'medical_home' => 'Yes',
                  'marital_status' => 'single',
                  'number_of_persons' => '2',
                  'income' => '25,001-25,000',
                  'insurance' => 'Medicaid',
                  'primary_care' => 'Other',
                  'prenatal_vitamin' => 'Yes',
                  'nutritional_counseling' => 'Yes',
                  'smoking_in_home' => 'Yes',
                  'employment_status' => 'Unemployed- Not seeking work- Barriers',
                  'education_enrollment' => 'High School',
                  'educational_level' => 'Some high school',
                  'parent_first_name' => 'Sue',
                  'parent_last_name' => 'Jones',
                  'parent_ssn' => '555555555',
                  'parent_medicaid' => '575757575',
                  'partner_first_name' => 'Sam',
                  'partner_last_name' => 'Jones',
                  'partner_ssn' => '444444444',
                  'partner_medicaid' => '444444444444',
                  'partner_employment' => 'Unemployed- Not seeking work- Barriers',
                  'partner_education' => '8th Grade or below',
                  'partner_education_status' => 'GED'
             ]);

             DB::table('clients')->insert([
                   // 'id' => '1',
                   'user_id' => '2',
                   'firstName' => 'John',
                   'lastName' => 'Doe',
                   'ssn' => '553485488',
                   'medicaid' => '00048466',
                   'birth_month' => '10',
                   'birth_day' => '2',
                   'birth_year' => '2017',
                   'due_month' => '10',
                   'due_day' => '20',
                   'due_year' => '2017',
                   'ethnicity' => 'Black',
                   'medical_home' => 'Yes',
                   'marital_status' => 'single',
                   'number_of_persons' => '2',
                   'income' => '25,001-25,000',
                   'insurance' => 'Medicaid',
                   'primary_care' => 'Other',
                   'prenatal_vitamin' => 'Yes',
                   'nutritional_counseling' => 'Yes',
                   'smoking_in_home' => 'Yes',
                   'employment_status' => 'Unemployed- Not seeking work- Barriers',
                   'education_enrollment' => 'High School',
                   'educational_level' => 'Some high school',
                   'parent_first_name' => 'Sue',
                   'parent_last_name' => 'Jones',
                   'parent_ssn' => '555555555',
                   'parent_medicaid' => '575757575',
                   'partner_first_name' => 'Sam',
                   'partner_last_name' => 'Jones',
                   'partner_ssn' => '444444444',
                   'partner_medicaid' => '444444444444',
                   'partner_employment' => 'Unemployed- Not seeking work- Barriers',
                   'partner_education' => '8th Grade or below',
                   'partner_education_status' => 'GED'
              ]);
        //
    }
}
