<?php

use Faker\Generator as Faker;

$factory->define(App\Log::class, function (Faker $faker) {
    return [
      'client_id' => DB::table('clients')->inRandomOrder()->first()->id,
      'user_id' => DB::table('users')->inRandomOrder()->first()->id,
      'date' => $faker->date($format = 'Y-m-d', $max = 'now'),
      'time' => $faker->time($format = 'H:i:s', $max = 'now'),
      'visit_type' => $faker->randomElement(['Scheduled Visit', 'Out of Home Visit', 'Caregiver Visit']),
      'basic_care' => $faker->randomElement(['true', 'false']),
      'childcare' => $faker->randomElement(['true', 'false']),
      'dv' => $faker->randomElement(['true', 'false']),
      'education' => $faker->randomElement(['true', 'false']),
      'employment' => $faker->randomElement(['true', 'false']),
      'first_steps' => $faker->randomElement(['true', 'false']),
      'health_department' => $faker->randomElement(['true', 'false']),
      'mental_health' => $faker->randomElement(['true', 'false']),
      'na' => $faker->randomElement(['true', 'false']),
      'oral_hygiene' => $faker->randomElement(['true', 'false']),
      'physician' => $faker->randomElement(['true', 'false']),
      'smoking' => $faker->randomElement(['true', 'false']),
      'substance_abuse' => $faker->randomElement(['true', 'false']),
      'transportation' => $faker->randomElement(['true', 'false']),
      'other_referral' => $faker->randomElement(['true', 'false']),
      'mother' => $faker->randomElement(['true', 'false']),
      'father' => $faker->randomElement(['true', 'false']),
      'temporary_custodian' => $faker->randomElement(['true', 'false']),
      'baby' => $faker->randomElement(['true', 'false']),
      'grandparent' => $faker->randomElement(['true', 'false']),
      'interpreter' => $faker->randomElement(['true', 'false']),
      'friend' => $faker->randomElement(['true', 'false']),
      'sibling' => $faker->randomElement(['true', 'false']),
      'other_person'=> $faker->randomElement(['true', 'false']),
      'concerns'=> $faker->randomElement(['0', '1', '2']),
      'clean' => $faker->randomElement(['true', 'false']),
      'pets' => $faker->randomElement(['true', 'false']),
      'home_smoking' => $faker->randomElement(['true', 'false']),
      'safe' => $faker->randomElement(['true', 'false']),
      'toys' => $faker->randomElement(['true', 'false']),
      'home_other' => $faker->randomElement(['true', 'false']),
      'engages' => $faker->randomElement(['true', 'false']),
      'difficult' => $faker->randomElement(['true', 'false']),
      'attentive' => $faker->randomElement(['true', 'false']),
      'redirection' => $faker->randomElement(['true', 'false']),
      'person_additional' => $faker->word,
      'ggf' => $faker->randomElement(['true', 'false']),
      'ggk' => $faker->randomElement(['true', 'false']),
      'curriculum_age' => $faker->randomElement(['Prenatal', '0-3 Months', '4-6 Months', '7-9 Months', '10-12 Months', '13-15 Months', '16-18 Months', '19-21 Months', '22-24 Months', '25-36 Months']),
      'module' => $faker-> text($maxNbChars = 25),
      'activity' => $faker-> text($maxNbChars = 25),
      'subsection' => $faker-> text($maxNbChars = 25),
      'handout' => $faker-> text($maxNbChars = 25),
      'demo' => $faker-> text($maxNbChars = 25),
      'additional' => $faker-> text($maxNbChars = 25),
      'materials' => $faker-> text($maxNbChars = 25),
      'asq' => $faker->randomElement(['true', 'false']),
      'asq_se' => $faker->randomElement(['true', 'false']),
      'child_status' => $faker->randomElement(['true', 'false']),
      'home_inventory' => $faker->randomElement(['true', 'false']),
      'childproofing' => $faker->randomElement(['true', 'false']),
      'consent' => $faker->randomElement(['true', 'false']),
      'eds' => $faker->randomElement(['true', 'false']),
      'goal' => $faker->randomElement(['true', 'false']),
      'caregiver_status' => $faker->randomElement(['true', 'false']),
      'health_progress' => $faker->randomElement(['true', 'false']),
      'hippa' => $faker->randomElement(['true', 'false']),
      'dv_screen' => $faker->randomElement(['true', 'false']),
      'mandatory' => $faker->randomElement(['true', 'false']),
      'partnership' => $faker->randomElement(['true', 'false']),
      'contact_information' => $faker->randomElement(['true', 'false']),
      'service_record' => $faker->randomElement(['true', 'false']),
      'cue' => $faker-> text($maxNbChars = 25),
      'expression' => $faker-> text($maxNbChars = 25),
      'empathy' => $faker-> text($maxNbChars = 25),
      'atp' => $faker->randomElement(['true', 'false']),
      'explore_and_wonder' => $faker->randomElement(['true', 'false']),
      'problem_talk' => $faker->randomElement(['true', 'false']),
      'normalizing' => $faker->randomElement(['true', 'false']),
      'be_present' => $faker->randomElement(['true', 'false']),
      'satp' => $faker->randomElement(['true', 'false']),
      'interaction_example' => $faker-> text($maxNbChars = 50),
      'eparenting' => $faker->randomElement(['true', 'false']),
      'character_builders' => $faker->randomElement(['true', 'false']),
      'brain_builders' => $faker->randomElement(['true', 'false']),
      'four_steps' => $faker->randomElement(['true', 'false']),
      'play_by_play' => $faker->randomElement(['true', 'false']),
      'body_builders' => $faker->randomElement(['true', 'false']),
      'daily_dos_example' => $faker-> text($maxNbChars = 50),
      'to_be_established'  => $faker->randomElement(['true', 'false']),
      'set_at_visit'  => $faker->randomElement(['true', 'false']),
      'progression'  => $faker->randomElement(['true', 'false']),
      'partner_involved'  => $faker->randomElement(['true', 'false']),
      'barriers'  => $faker->randomElement(['true', 'false']),
      'narrative' => $faker->text($maxNbChars = 150),
      'referrals_last_visit' => $faker->randomElement(['0', '1', '2']),
      'referral_text' => $faker->text($maxNbChars = 100),
      'follow_up' => $faker->text($maxNbChars = 50),
      'follow_up_module' => $faker->text($maxNbChars = 15),
      'follow_up_activity' => $faker->text($maxNbChars = 15),
      'next_visit' => $faker->dateTimeBetween($startDate = 'now', $endDate = '2 weeks', $timezone = null),
      'next_visit_month' => $faker->month,
      'next_visit_day' => $faker->dayOfMonth,
      'next_visit_year' => intval($faker->biasedNumberBetween($min = 2016, $max = 2018)),
      'fsw_signature' => $faker->name,
      'fsw_date' => $faker->dateTimeBetween($startDate = '-2 weeks', $endDate = 'now', $timezone = null),
      'supervisor_signature' => $faker->name,
      'supervisor_date'=> $faker->dateTimeBetween($startDate = '-2 weeks', $endDate = 'now', $timezone = null)
        //
    ];
});
